### ISSUE TITLE
Prayer reminder for Linux

### ISSUE THREAD

**Issue by AbdeltwabMF** [mobadarah/tajmeeaton#6]
I'm glad to participate in this awesome project. and I would like to add my new prayer reminder script to the list.
Here is the [link](https://github.com/AbdeltwabMF/nxprayer) to it.

**Comment by MuhammadSawalhy** [comment]
جزاك الله خيرا على مجهودك. إن شاء الله لن تكون آخر مساهماتك

**Comment by AbdeltwabMF** [comment]
وجزاكم مثله؛ إن شاء الله 💗
